# Generated by Django 5.1.3 on 2024-11-20 09:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melodixapp', '0003_user_profile_picture_alter_user_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subgenre', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('release_format', models.CharField(choices=[('SINGLE', 'Single'), ('EP', 'EP'), ('ALBUM', 'Album')], max_length=10)),
                ('upc_ean', models.CharField(blank=True, max_length=12, null=True)),
                ('catalogue_number', models.CharField(blank=True, max_length=50, null=True)),
                ('release_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('copyright_holder', models.CharField(max_length=255)),
                ('copyright_year', models.PositiveIntegerField(default=2024)),
                ('production_holder', models.CharField(max_length=255)),
                ('production_year', models.PositiveIntegerField(default=2024)),
                ('artwork', models.ImageField(blank=True, null=True, upload_to='release_artworks/')),
                ('subgenre', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('availability_date', models.DateField()),
                ('price_tier', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to=settings.AUTH_USER_MODEL)),
                ('featuring_artists', models.ManyToManyField(blank=True, related_name='featuring_releases', to='melodixapp.artist')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='melodixapp.genre')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='melodixapp.label')),
                ('primary_artists', models.ManyToManyField(related_name='primary_releases', to='melodixapp.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('ORIGINAL', 'Original'), ('KARAOKE', 'Karaoke'), ('MEDLEY', 'Medley'), ('COVER', 'Cover')], max_length=10)),
                ('is_instrumental', models.BooleanField()),
                ('file', models.FileField(upload_to='track_files/')),
                ('isrc', models.CharField(blank=True, max_length=12, null=True)),
                ('language', models.CharField(max_length=100)),
                ('lyrics_language', models.CharField(blank=True, max_length=100, null=True)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('production_year', models.PositiveIntegerField(default=2024)),
                ('copyright_holder', models.CharField(max_length=255)),
                ('copyright_year', models.PositiveIntegerField(default=2024)),
                ('sound_recording_copyright', models.CharField(blank=True, max_length=255, null=True)),
                ('parental_advisory', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('CLEANED', 'Cleaned')], max_length=10)),
                ('artist', models.ManyToManyField(related_name='track_artists', to='melodixapp.artist')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to=settings.AUTH_USER_MODEL)),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='melodixapp.genre')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='melodixapp.release')),
            ],
        ),
    ]
