# Generated by Django 5.1.3 on 2024-11-20 09:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melodixapp', '0004_genre_artist_label_release_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='subgenre',
        ),
        migrations.AddField(
            model_name='artist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='label',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='release',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='availability_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='release',
            name='copyright_holder',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='release',
            name='language',
            field=models.CharField(default='English', max_length=100),
        ),
        migrations.AlterField(
            model_name='release',
            name='price_tier',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10),
        ),
        migrations.AlterField(
            model_name='release',
            name='production_holder',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_format',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('EP', 'EP'), ('ALBUM', 'Album')], default='SINGLE', max_length=10),
        ),
        migrations.AlterField(
            model_name='track',
            name='copyright_holder',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='track',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='track_files/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='is_instrumental',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='track',
            name='language',
            field=models.CharField(default='English', max_length=100),
        ),
        migrations.AlterField(
            model_name='track',
            name='parental_advisory',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('CLEANED', 'Cleaned')], default='NO', max_length=10),
        ),
        migrations.AlterField(
            model_name='track',
            name='type',
            field=models.CharField(choices=[('ORIGINAL', 'Original'), ('KARAOKE', 'Karaoke'), ('MEDLEY', 'Medley'), ('COVER', 'Cover')], default='ORIGINAL', max_length=10),
        ),
        migrations.CreateModel(
            name='Subgenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgenres', to='melodixapp.genre')),
            ],
        ),
        migrations.AddField(
            model_name='track',
            name='subgenre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='melodixapp.subgenre'),
        ),
        migrations.AlterField(
            model_name='release',
            name='subgenre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='melodixapp.subgenre'),
        ),
    ]
