# Generated by Django 5.1.3 on 2024-11-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melodixapp', '0005_remove_genre_subgenre_artist_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('logo', models.ImageField(upload_to='store_logos/')),
                ('store_type', models.CharField(choices=[('DOWNLOADS', 'Downloads'), ('STREAMING', 'Streaming'), ('BOTH', 'Both')], default='BOTH', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='artist',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='label',
            name='created_at',
        ),
    ]
